name = "my-worker"
compatibility_date = "2025-08-30"
main = "src/index.js"
# Pages 静态站点
[site]
bucket = "./public"

  // Add this to your wrangler.jsonc
  "kv_namespaces": [
    {
      "binding": "KV",
      "id": "f8e9d611b3b84875864e3b93f0939eab",
      
      // Optional: preview_id used when running `wrangler dev` for local dev
      "preview_id": "<ID_OF_PREVIEW_KV_NAMESPACE_FOR_LOCAL_DEVELOPMENT>"
    }
  ]

